packages: []
catalogs:
  build:
    tsdown: ^0.15.11
  cli:
    bumpp: ^10.3.1
    pncat: ^0.7.4
    taze: ^19.8.1
  lint:
    '@antfu/eslint-config': ^6.1.0
    eslint: ^9.38.0
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  test:
    '@vitest/coverage-v8': ^4.0.4
    vitest: ^4.0.4
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.9.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
